### consulta de usuario
GET http://wwwsistemamenu/productos

### modificar Producto
PUT http://wwwsistemamenu/productos/1

{
    "codBarras":"750105521001",
    "descripcion":"Arroz integral 2kg",
    "stock":85,
    "precio_unitario":15,
    "fecha_registro":"2026-06-12"
}


### adicionar producto 
POST http://wwwsistemamenu/productos

{ 
    "codBarras":"750105531021",
    "descripcion":"azucar 3kg",
    "stock":85,
    "precio_unitario":15,
    "fecha_registro":"2026-06-12"
}
### eliminar producto
DELETE http://wwwsistemamenu/productos/1